name: PlatformIO Build Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target_project:
          - enr_dps310_interface
          - enr_message_board
          - enr_stickv2_interface
          - m5atoms3_sesami_client
          - m5atoms3_switchbot_client
          - sample_aes_cmac
          - sample_esp_now_broadcaster
          - sample_esp_now_receiver
          - sample_sesami
          - sample_uwb
          - sdp_debug_board
          - sdp_elevator_status_broadcaster
          - sdp_example
          - sdp_landmark_information
          - sdp_sesami_host
          - sdp_stickv2_interface
          - smart_device_protocol_interface
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('${GITHUB_WORKSPACE}/package.xml') }}-${{ hashFiles('${GITHUB_WORKSPACE}/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('${GITHUB_WORKSPACE}/package.xml') }}-${{ hashFiles('${GITHUB_WORKSPACE}/requirements.txt') }}
    - name: Cache PlatformIO global ${{ matrix.target_project }}
      uses: actions/cache@v2
      with:
        path: ~/.platformio/cache
        key: ${{ runner.os }}-platformio-global-${{ matrix.target_project }}-${{ hashFiles('${GITHUB_WORKSPACE}/sketchbooks/${{ matrix.target_project }}/platformio.ini') }}
        restore-keys: ${{ runner.os }}-platformio-global-${{ matrix.target_project }}-${{ hashFiles('${GITHUB_WORKSPACE}/sketchbooks/${{ matrix.target_project }}/platformio.ini') }}
    - name: Cache PlatformIO local ${{ matrix.target_project }}
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/sketchbooks/${{ matrix.target_project }}/.pio
        key: ${{ runner.os }}-platformio-local-${{ matrix.target_project }}-${{ hashFiles('${GITHUB_WORKSPACE}/sketchbooks/${{ matrix.target_project }}/platformio.ini') }}
        restore-keys: ${{ runner.os }}-platformio-local-${{ matrix.target_project }}-${{ hashFiles('${GITHUB_WORKSPACE}/sketchbooks/${{ matrix.target_project }}/platformio.ini') }}
    - name: Update pip and install pip package
      run: |
        pip3 install pip --upgrade
        pip3 install pyopenssl --upgrade
        pip3 install platformio
    - name: build sketch ${{ matrix.target_project }}
      run: |
        pio run -d ${{ github.workspace }}/sketchbooks/${{ matrix.target_project }}